#!/usr/bin/env python3
"""Render generated wiki views from the event stream.

The `log` subcommand renders wiki/log.md as a projection: the frozen legacy
record verbatim from wiki/log-legacy.md when the deployment has one, then
one entry per post-epoch handoff event in (timestamp_utc, event_id) order,
each carrying its event_id and a garden-disposition line joined from
garden-apply events. A blank deployment has neither wiki/log-legacy.md nor
wiki/log-epoch.json: every handoff event renders and the header drops the
legacy-boundary sentence. The two files travel as a pair; exactly one
present is an error. Output is a pure function of its inputs so the
pre-commit hook can regenerate and compare.

The `claude-local` subcommand renders CLAUDE.local.md, the generated
orientation index: the script owns every section; the garden LLM supplies
only the Quickstart text via --quickstart-file. Without that flag the
existing file's Quickstart is carried forward, so a handoff can refresh the
deterministic sections (notably the pending warning) without an LLM in the
loop. Unlike `log`, the output depends on git state outside the wiki repo,
so it gets no pre-commit byte-equality rule — write protection is the
deny-rule layer; docs/enforcement-contract.md in the kit repo states what
each enforcement layer does and does not cover.

Both subcommands take --wiki (the wiki repo root; resolved via
wiki_config.resolve_wiki_root when omitted) and derive unset path flags
from it.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from datetime import datetime
from pathlib import Path
from typing import Any, NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent

# Sibling imports must work from every context this module is loaded in:
# CLI run (sys.path[0] is scripts/), package-style import (tests put the
# kit root on sys.path), and importlib loading.
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import wiki_config  # noqa: E402
from wiki_event import (  # noqa: E402
    EventType,
    HandoffStatus,
    ValidationError,
    event_repo,
    event_sort_key,
    load_events,
    load_json,
    utc_timestamp,
    validate_artifact,
)

RENDER_EPOCH_KEY = "render_epoch_start"

DEFAULT_BUILD_INDEX_SCRIPT = SCRIPT_DIR / "build-index.py"
GARDEN_LOCK_SCRIPT = SCRIPT_DIR / "garden-lock.py"
GIT_ENV = {**os.environ, "GIT_OPTIONAL_LOCKS": "0"}
TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
RECENT_SESSION_COUNT = 5
LINE_BUDGET = 80
NIGHT_REPORT_WARN_TOKENS = 2_500
NIGHT_REPORT_HARD_TOKENS = 4_000

BANNER_TEMPLATE = "> Generated by scripts/wiki-render.py — {now}"
QUICKSTART_HEADING = "## Quickstart"
# The memory pointer comes from config ([memory].index_line, knob 9); an
# unset value omits the line from the render. Carry-forward strips ANY line
# with this prefix, not only the configured value, so a config change never
# leaves a stale pointer behind in the carried Quickstart.
MEMORY_LINE_PREFIX = "Memory: "
DETAIL_LINE = "Detail: workstreams/<name>.md — read the relevant file for your task."
ENTITIES_LINE = "Entities: wiki/entities/ — synthesized topic pages for deep-dives"
PENDING_HEADING = "## Pending unreviewed handoffs"
WORKSTREAMS_HEADING = "## Workstreams"
RECENT_HEADING = (
    "## Recent Sessions (last 5 log entries — log.md is the generated projection)"
)
UNCOMMITTED_HEADING = "## Uncommitted Changes"
# A configured companion whose overlay carries no path on this machine
# renders this fixed note instead of git facts.
NO_CHECKOUT_NOTE = "no local checkout configured on this machine"
# Renderer-owned line in old hand-assembled Quickstarts; stripped on
# carry-forward so the stale count never survives next to the live section.
LEGACY_PENDING_PREFIX = "Pending events:"
LEGACY_DETAIL_LINE = (
    "Detail: .claude/workstreams/<name>.md — read the relevant file for your task."
)

LOG_HEADER_TEMPLATE = """\
# Session Log

Generated by scripts/wiki-render.py from wiki/log-legacy.md and wiki/events/**.
Never hand-edit. Each entry starts with `## [ISO-8601]` for grep-parsability:
`grep "^## \\[" wiki/log.md | tail -10`. Entries at or before {boundary} are
the frozen legacy record; later entries cite their source event_id.
"""

LOG_HEADER_NO_LEGACY = """\
# Session Log

Generated by scripts/wiki-render.py from wiki/events/**.
Never hand-edit. Each entry starts with `## [ISO-8601]` for grep-parsability:
`grep "^## \\[" wiki/log.md | tail -10`. Every entry cites its source event_id.
"""


def read_render_epoch(epoch_path: Path) -> str:
    epoch = load_json(epoch_path)
    validate_artifact(epoch, "log-epoch.schema.json", str(epoch_path))
    return epoch[RENDER_EPOCH_KEY]


def garden_dispositions(events: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Map target_event_id -> the latest garden-apply event for that target."""
    dispositions: dict[str, dict[str, Any]] = {}
    applies = [e for e in events if e.get("event_type") == EventType.GARDEN_APPLY]
    for event in sorted(applies, key=event_sort_key):
        dispositions[event["target_event_id"]] = event
    return dispositions


def render_entry(
    handoff: dict[str, Any],
    disposition: dict[str, Any] | None,
) -> str:
    repo = event_repo(handoff)
    lines = [
        f"## [{handoff['timestamp_utc']}] {handoff['summary']} "
        f"@{repo.sha} branch:{repo.branch} tool:{handoff['tool']} "
        f"event:{handoff['event_id']}"
    ]
    state = handoff.get("workstream_state") or {}
    lines.extend(f"- {item}" for item in state.get("what_was_done", []))
    if disposition is not None:
        date = disposition["timestamp_utc"][: len("YYYY-MM-DD")]
        lines.append(
            f"- Garden: {disposition['status']} {date} "
            f"(event {disposition['event_id']})"
        )
    return "\n".join(lines) + "\n"


def render_log(
    events_dir: Path,
    epoch_path: Path | None,
    legacy_path: Path | None,
    quarantine_path: Path,
) -> str:
    """Render the log projection.

    epoch_path/legacy_path are None on a blank deployment (no legacy
    record): every handoff event renders and the header drops the boundary
    sentence. They travel as a pair; exactly one None fails loud.
    """
    if (epoch_path is None) != (legacy_path is None):
        raise ValidationError(
            "wiki/log-legacy.md and wiki/log-epoch.json travel as a pair: "
            f"got legacy={legacy_path}, epoch={epoch_path}; a legacy "
            "deployment has both, a blank deployment has neither"
        )
    events = load_events(events_dir, quarantine_path)
    dispositions = garden_dispositions(events)
    handoffs = [e for e in events if e.get("event_type") == EventType.HANDOFF]
    if legacy_path is None or epoch_path is None:
        rendered = [
            render_entry(event, dispositions.get(event["event_id"]))
            for event in handoffs
        ]
        return "\n".join([LOG_HEADER_NO_LEGACY, *rendered])
    boundary = read_render_epoch(epoch_path)
    legacy = legacy_path.read_text(encoding="utf-8")
    if not legacy.startswith("## ["):
        raise ValidationError(
            f"{legacy_path} must start with a '## [' entry heading — it holds "
            "frozen legacy entries only, never a file header"
        )
    rendered = [
        render_entry(event, dispositions.get(event["event_id"]))
        for event in handoffs
        if event["timestamp_utc"] > boundary
    ]
    header = LOG_HEADER_TEMPLATE.format(boundary=boundary)
    return "\n".join([header, legacy.rstrip("\n") + "\n", *rendered])


def pending_handoffs(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Handoffs awaiting garden, mirroring build_pending_index semantics:
    any garden-apply (applied, rejected, ...) removes its target from pending.
    """
    applied_ids = {
        event["target_event_id"]
        for event in events
        if event.get("event_type") == EventType.GARDEN_APPLY
    }
    return [
        event
        for event in events
        if event.get("event_type") == EventType.HANDOFF
        and event.get("status") == HandoffStatus.PENDING_GARDEN
        and event["event_id"] not in applied_ids
    ]


def render_pending_lines(events: list[dict[str, Any]]) -> list[str]:
    pending = pending_handoffs(events)
    if pending:
        plural = "s" if len(pending) != 1 else ""
        return [
            f"- {len(pending)} event{plural} since last garden apply.",
            "- Read `wiki/pending/latest.md` before broad planning.",
            "- Treat pending framing as provisional.",
        ]
    applies = [
        event for event in events if event.get("event_type") == EventType.GARDEN_APPLY
    ]
    if not applies:
        return ["None — no garden applies recorded."]
    latest = max(applies, key=event_sort_key)
    gardened_date = latest["timestamp_utc"][: len("YYYY-MM-DD")]
    return [f"None — gardened {gardened_date}."]


def render_recent_session_lines(log_text: str) -> list[str]:
    headings = [line for line in log_text.splitlines() if line.startswith("## [")]
    return [
        "- " + line.removeprefix("## ") for line in headings[-RECENT_SESSION_COUNT:]
    ]


def workstreams_tree(
    root: Path,
    build_index_script: Path = DEFAULT_BUILD_INDEX_SCRIPT,
) -> str:
    result = subprocess.run(
        [sys.executable, str(build_index_script), "--wiki", str(root)],
        capture_output=True,
        text=True,
    )
    if result.stderr:
        sys.stderr.write(result.stderr)
    if result.returncode != 0:
        raise ValidationError(f"{build_index_script} exited {result.returncode}")
    return result.stdout.rstrip("\n")


def _owned_trailer_lines(memory_index_line: str | None) -> tuple[str, ...]:
    """The renderer-appended trailer lines for the given config, plus the
    legacy detail line old files carry."""
    lines = [DETAIL_LINE, ENTITIES_LINE, LEGACY_DETAIL_LINE]
    if memory_index_line is not None:
        lines.insert(0, memory_index_line)
    return tuple(lines)


def validate_quickstart(text: str, memory_index_line: str | None) -> None:
    """Reject quickstart input that would corrupt the generated layout or be
    silently dropped by the next carry-forward extraction — the render →
    extract_quickstart round-trip must hold for everything accepted here."""
    if not text.strip():
        raise ValidationError("quickstart text is empty")
    owned = _owned_trailer_lines(memory_index_line)
    for line in text.splitlines():
        if line.startswith("## "):
            reason = "'## ' section headings corrupt the generated layout"
        elif line in owned or line.startswith(MEMORY_LINE_PREFIX):
            reason = "renderer-owned trailer lines are appended by the script"
        elif line.startswith(LEGACY_PENDING_PREFIX):
            reason = (
                f"{LEGACY_PENDING_PREFIX!r} lines are superseded by the "
                f"generated {PENDING_HEADING!r} section"
            )
        else:
            continue
        raise ValidationError(f"quickstart text must not contain {line!r}: {reason}")


def extract_quickstart(claude_local_text: str, memory_index_line: str | None) -> str:
    """Carry-forward source: the Quickstart section of the existing file,
    minus the renderer-owned trailer lines (any stale memory pointer and any
    old hand-written pending count included). Fails loudly rather than
    synthesizing a Quickstart."""
    lines = claude_local_text.splitlines()
    try:
        start = lines.index(QUICKSTART_HEADING) + 1
    except ValueError:
        raise ValidationError(
            f"existing CLAUDE.local.md has no {QUICKSTART_HEADING!r} heading; "
            "pass --quickstart-file instead of carrying forward"
        ) from None
    owned = _owned_trailer_lines(memory_index_line)
    section = []
    for line in lines[start:]:
        if line.startswith("## "):
            break
        if line in owned or line.startswith(MEMORY_LINE_PREFIX):
            continue
        if line.startswith(LEGACY_PENDING_PREFIX):
            continue
        section.append(line)
    text = "\n".join(section).strip("\n")
    if not text.strip():
        raise ValidationError(
            "existing CLAUDE.local.md has an empty Quickstart; pass "
            "--quickstart-file instead of carrying forward"
        )
    return text


def render_claude_local(
    quickstart: str,
    pending_lines: list[str],
    tree: str,
    recent_lines: list[str],
    uncommitted_lines: list[str],
    now: str,
    memory_index_line: str | None,
) -> str:
    try:
        canonical = datetime.strptime(now, TIMESTAMP_FORMAT).strftime(TIMESTAMP_FORMAT)
    except ValueError:
        canonical = None
    if canonical != now:
        raise ValidationError(f"timestamp {now!r} is not canonical {TIMESTAMP_FORMAT}")
    validate_quickstart(quickstart, memory_index_line)
    memory_lines = [] if memory_index_line is None else [memory_index_line]
    lines = [
        BANNER_TEMPLATE.format(now=now),
        "",
        QUICKSTART_HEADING,
        "",
        *quickstart.strip("\n").splitlines(),
        "",
        *memory_lines,
        DETAIL_LINE,
        ENTITIES_LINE,
        "",
        PENDING_HEADING,
        "",
        *pending_lines,
        "",
        WORKSTREAMS_HEADING,
        "",
        *tree.splitlines(),
        "",
        RECENT_HEADING,
        "",
        *recent_lines,
        "",
        UNCOMMITTED_HEADING,
        "",
        *uncommitted_lines,
    ]
    return "\n".join(lines) + "\n"


def line_budget_overrun(text: str) -> int:
    """Lines over LINE_BUDGET (0 when within budget) — the garden flow's
    line-budget check lives in the renderer."""
    return max(0, len(text.splitlines()) - LINE_BUDGET)


def estimate_token_count(text: str) -> int:
    """Rough token estimate (bytes // 4).  Shared with wiki_doctor so the
    renderer can warn at the same threshold the doctor enforces."""
    return (len(text.encode("utf-8")) + 3) // 4


class TreeFacts(NamedTuple):
    label: str
    branch: str
    sha: str
    dirty: int
    staged: int
    unpushed: int | None  # None = no upstream configured
    # Only meaningful when unpushed is None: whether HEAD is reachable from
    # any remote branch (pushed, just missing tracking config). None when an
    # upstream exists — the unpushed count already answers the question.
    remote_has_head: bool | None = None


class MissingCheckout(NamedTuple):
    """A configured companion whose overlay carries no path on this machine.
    Rendered as a fixed note — deterministic, no git calls."""

    label: str


def run_git(
    repo: Path,
    args: list[str],
    default: str | None = None,
    strip: bool = True,
) -> str:
    """strip=False preserves porcelain output verbatim: status lines for
    modified-but-unstaged files start with a space, and stripping the first
    line's leading space miscounts it as staged."""
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        env=GIT_ENV,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        return result.stdout.strip() if strip else result.stdout
    if default is not None:
        return default
    raise ValidationError(
        f"git -C {repo} {' '.join(args)} failed: {result.stderr.strip()}"
    )


def tree_facts(label: str, path: Path) -> TreeFacts:
    if not path.is_dir():
        raise ValidationError(
            f"{label}: {path} does not exist — pass the correct repo path"
        )
    branch = run_git(path, ["branch", "--show-current"]) or "detached"
    sha = run_git(path, ["rev-parse", "--short", "HEAD"])
    status = run_git(path, ["status", "--porcelain"], strip=False)
    entries = [line for line in status.splitlines() if line]
    staged = sum(1 for line in entries if line[0] not in " ?")
    ahead = run_git(path, ["rev-list", "--count", "@{upstream}..HEAD"], default="")
    remote_has_head = None
    if not ahead:
        # No upstream: distinguish "pushed, missing tracking" from genuinely
        # unpushed. Empty output = HEAD reachable from a remote branch
        # (early-exits at one commit; no default — a real failure raises).
        unreachable = run_git(path, ["rev-list", "-1", "HEAD", "--not", "--remotes"])
        remote_has_head = unreachable == ""
    return TreeFacts(
        label=label,
        branch=branch,
        sha=sha,
        dirty=len(entries),
        staged=staged,
        unpushed=int(ahead) if ahead else None,
        remote_has_head=remote_has_head,
    )


def worktree_paths(repo: Path) -> list[Path]:
    output = run_git(repo, ["worktree", "list", "--porcelain"])
    return [
        Path(line.removeprefix("worktree "))
        for line in output.splitlines()
        if line.startswith("worktree ")
    ]


def collect_uncommitted_facts(
    wiki_repo: Path,
    companions: Sequence[wiki_config.Companion],
) -> list[TreeFacts | MissingCheckout]:
    """The wiki repo row first, then one row per configured companion in
    config order: git facts (plus that repo's linked worktrees) when the
    overlay names a local checkout, the fixed no-checkout note otherwise.
    Zero companions = just the wiki repo row."""
    facts: list[TreeFacts | MissingCheckout] = [tree_facts("wiki repo", wiki_repo)]
    for companion in companions:
        if companion.path is None:
            facts.append(MissingCheckout(companion.display_label))
            continue
        facts.append(tree_facts(companion.display_label, companion.path))
        for path in worktree_paths(companion.path):
            if path.resolve() == companion.path.resolve():
                continue
            facts.append(tree_facts(f"worktree {path.name}", path))
    return facts


def render_uncommitted_lines(facts: list[TreeFacts | MissingCheckout]) -> list[str]:
    lines = []
    clean = []
    for fact in facts:
        if isinstance(fact, MissingCheckout):
            lines.append(f"- {fact.label}: {NO_CHECKOUT_NOTE}")
            continue
        parts = []
        if fact.dirty:
            staged_note = f" ({fact.staged} staged)" if fact.staged else ""
            parts.append(f"{fact.dirty} dirty{staged_note}")
        if fact.unpushed:
            parts.append(f"{fact.unpushed} unpushed")
        if fact.unpushed is None:
            if fact.remote_has_head is None:
                raise ValidationError(
                    f"{fact.label}: no upstream but the remote-reachability "
                    "probe was not run — tree_facts must set remote_has_head"
                )
            state = "pushed" if fact.remote_has_head else "unpushed"
            parts.append(f"no upstream ({state})")
        if parts:
            lines.append(
                f"- {fact.label} ({fact.branch} @ {fact.sha}): {', '.join(parts)}"
            )
        else:
            clean.append(fact.label)
    if clean:
        lines.append(f"- clean: {', '.join(clean)}")
    return lines


def acquire_garden_lock(root: Path) -> str:
    result = subprocess.run(
        [sys.executable, str(GARDEN_LOCK_SCRIPT), "acquire", "--wiki", str(root)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        held = result.stderr.strip() or result.stdout.strip()
        raise ValidationError(f"garden lock not acquired: {held}")
    for line in result.stdout.splitlines():
        if line.startswith("locked token="):
            return line.removeprefix("locked token=").strip()
    raise ValidationError(f"garden-lock acquire output unrecognized: {result.stdout!r}")


def release_garden_lock(token: str, root: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(GARDEN_LOCK_SCRIPT),
            "release",
            token,
            "--wiki",
            str(root),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise ValidationError(f"garden lock release failed: {result.stderr.strip()}")


def write_atomic(path: Path, text: str) -> None:
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    try:
        os.fchmod(fd, 0o644)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp_name, path)
    except BaseException:
        os.unlink(tmp_name)
        raise


class ContentPaths(NamedTuple):
    events_dir: Path
    epoch_file: Path
    legacy_file: Path
    quarantine_file: Path


def content_paths(args: argparse.Namespace, root: Path) -> ContentPaths:
    """Unset path flags derive from the resolved wiki root."""
    wiki_dir = root / "wiki"
    return ContentPaths(
        events_dir=(
            args.events_dir if args.events_dir is not None else wiki_dir / "events"
        ),
        epoch_file=(
            args.epoch_file
            if args.epoch_file is not None
            else wiki_dir / "log-epoch.json"
        ),
        legacy_file=(
            args.legacy_file
            if args.legacy_file is not None
            else wiki_dir / "log-legacy.md"
        ),
        quarantine_file=(
            args.quarantine_file
            if args.quarantine_file is not None
            else wiki_dir / "quarantine.json"
        ),
    )


def _pair_member_or_none(path: Path) -> Path | None:
    """CLI wiring only: a nonexistent legacy/epoch file means "absent".
    render_log itself takes None explicitly so tests drive both modes."""
    return path if path.is_file() else None


def cmd_log(args: argparse.Namespace) -> int:
    root = wiki_config.resolve_wiki_root(args.wiki)
    # The log projection consumes no config values, but a deployment with a
    # broken wiki.toml must fail loud here too, not only in config consumers.
    wiki_config.load_config(root)
    paths = content_paths(args, root)
    output = args.output if args.output is not None else root / "wiki" / "log.md"
    text = render_log(
        events_dir=paths.events_dir,
        epoch_path=_pair_member_or_none(paths.epoch_file),
        legacy_path=_pair_member_or_none(paths.legacy_file),
        quarantine_path=paths.quarantine_file,
    )
    if args.check:
        current = output.read_text(encoding="utf-8")
        if current != text:
            print(
                f"{output} does not match rendered output; "
                "run scripts/wiki-render.py log to regenerate",
                file=sys.stderr,
            )
            return 1
        print(f"{output} matches rendered output")
        return 0
    write_atomic(output, text)
    print(output)
    return 0


def render_and_write_claude_local(
    args: argparse.Namespace, root: Path, config: wiki_config.WikiConfig
) -> int:
    paths = content_paths(args, root)
    output = args.output if args.output is not None else root / "CLAUDE.local.md"
    wiki_repo = args.wiki_repo if args.wiki_repo is not None else root
    if args.quickstart_file is not None:
        quickstart = args.quickstart_file.read_text(encoding="utf-8").strip("\n")
    else:
        quickstart = extract_quickstart(
            output.read_text(encoding="utf-8"), config.memory_index_line
        )
    events = load_events(paths.events_dir, paths.quarantine_file)
    log_text = render_log(
        events_dir=paths.events_dir,
        epoch_path=_pair_member_or_none(paths.epoch_file),
        legacy_path=_pair_member_or_none(paths.legacy_file),
        quarantine_path=paths.quarantine_file,
    )
    text = render_claude_local(
        quickstart=quickstart,
        pending_lines=render_pending_lines(events),
        tree=workstreams_tree(root, args.build_index_script),
        recent_lines=render_recent_session_lines(log_text),
        uncommitted_lines=render_uncommitted_lines(
            collect_uncommitted_facts(wiki_repo, list(config.companions.values()))
        ),
        now=args.now if args.now is not None else utc_timestamp(),
        memory_index_line=config.memory_index_line,
    )
    overrun = line_budget_overrun(text)
    if overrun:
        print(
            f"warning: {output} is {LINE_BUDGET + overrun} lines "
            f"({overrun} over the {LINE_BUDGET}-line budget)",
            file=sys.stderr,
        )
    tokens = estimate_token_count(text)
    hard_budget = config.budgets.claude_local.hard
    if tokens > hard_budget:
        print(
            f"warning: {output} estimates {tokens} tokens "
            f"({tokens - hard_budget} over the "
            f"{hard_budget}-token hard budget; "
            f"doctor will FAIL)",
            file=sys.stderr,
        )
    write_atomic(output, text)
    print(output)
    return 0


def cmd_claude_local(args: argparse.Namespace) -> int:
    root = wiki_config.resolve_wiki_root(args.wiki)
    config = wiki_config.load_config(root)
    if args.no_lock:
        return render_and_write_claude_local(args, root, config)
    # The lock covers the carry-forward read, not just the write: a
    # concurrent garden writing between read and write would have its
    # Quickstart overwritten by the stale carried copy.
    token = acquire_garden_lock(root)
    try:
        return render_and_write_claude_local(args, root, config)
    finally:
        release_garden_lock(token, root)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    log = sub.add_parser("log", help="Render wiki/log.md from the event stream.")
    log.add_argument(
        "--wiki",
        type=Path,
        default=None,
        help="Wiki repo root; resolved from cwd when omitted.",
    )
    log.add_argument("--events-dir", type=Path, default=None)
    log.add_argument("--epoch-file", type=Path, default=None)
    log.add_argument("--legacy-file", type=Path, default=None)
    log.add_argument("--output", type=Path, default=None)
    log.add_argument("--quarantine-file", type=Path, default=None)
    log.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if --output differs from rendered text; write nothing.",
    )
    log.set_defaults(func=cmd_log)

    local = sub.add_parser(
        "claude-local",
        help="Render CLAUDE.local.md (deterministic sections + Quickstart slot).",
    )
    local.add_argument(
        "--wiki",
        type=Path,
        default=None,
        help="Wiki repo root; resolved from cwd when omitted.",
    )
    local.add_argument("--events-dir", type=Path, default=None)
    local.add_argument("--epoch-file", type=Path, default=None)
    local.add_argument("--legacy-file", type=Path, default=None)
    local.add_argument("--quarantine-file", type=Path, default=None)
    local.add_argument("--output", type=Path, default=None)
    local.add_argument(
        "--quickstart-file",
        type=Path,
        default=None,
        help="LLM-written Quickstart text; omitted = carry the existing "
        "Quickstart forward from --output.",
    )
    local.add_argument(
        "--wiki-repo",
        type=Path,
        default=None,
        help="Repo for the wiki git-facts row; defaults to the wiki root.",
    )
    local.add_argument(
        "--build-index-script",
        type=Path,
        default=DEFAULT_BUILD_INDEX_SCRIPT,
    )
    local.add_argument(
        "--now",
        default=None,
        help="Pin the banner timestamp (tests); default is current UTC.",
    )
    local.add_argument(
        "--no-lock",
        action="store_true",
        help="Skip the garden lock around the write (tests).",
    )
    local.set_defaults(func=cmd_claude_local)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except (
        ValidationError,
        wiki_config.ConfigError,
        KeyError,
        OSError,
        ValueError,
    ) as exc:
        # ValueError covers json.JSONDecodeError; OSError covers
        # FileNotFoundError; KeyError covers events missing sort fields.
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
